name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Compile LaTeX source (one-sided)
        run: latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=out thesis-onesided.tex
        working-directory: ./Source

      - name: Compile LaTeX source (two-sided)
        run: latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=out thesis-twosided.tex
        working-directory: ./Source
